### ISSUE TITLE
FiD Missing

### ISSUE THREAD

**Issue by OhadRubin** [facebookresearch/NeuralDB#4]
Line 51 in `modelling/neuraldb/run.py` has the following import:
```from neuraldb.modelling.fusion_in_decoder import T5MergeForConditionalGeneration```
Is it possible to add it to the repository?

**Comment by j6mes** [comment]
I've removed the references to FiD for now. The FiD wasn't compatible with the version of transformers that is used for this repository. I'll probably have to add another subfolder for the legacy FiD module in isolation.

If you're looking for code for FiD by itself, this repo should work for you: https://github.com/facebookresearch/FiD

**Comment by OhadRubin** [comment]
I see. I do have a few general questions about FID:
1. How did you initialize the FiD baseline? Did you use the NQ pretrained model?
2. If not, how did you train the FiD on WikiNLDB? 
Thanks

**Comment by j6mes** [comment]
FiD was initialised with the t5-base parameters and finetuned on our dataset.
