### ISSUE TITLE
Regarding the Wikidata mongo dump

### ISSUE THREAD

**Issue by OhadRubin** [facebookresearch/NeuralDB#5]
Hey, regarding this:
```
mongorestore --archive --gzip < mongo_wikidata_dump.gz
```
Where can I get the file mongo_wikidata_dump.gz?

**Comment by OhadRubin** [comment]
Also, which version of wikidata did you use in wikidata_file?

**Comment by j6mes** [comment]
Was based off January 2021. The DB can be re-created from the dump. But it takes a few days to decompress the file and index it. The Wikidata file will be released with the other data when the infrastructure's been set up.

**Comment by OhadRubin** [comment]
Looking at the wikimedia website it looks like the oldest dump they have is from march.
https://dumps.wikimedia.org/wikidatawiki/
Am I missing something?

**Comment by OhadRubin** [comment]
I think I found a mirror.
https://archive.org/details/wikidatawiki-20210120
Can you confirm? 
Also, if this is indeed the correct dump, are all the 250GB necessary for the preprocessing?

**Comment by OhadRubin** [comment]
Or is it this one:
https://archive.org/download/wikibase-wikidatawiki-20210125/wikidata-20210125-all.json.bz2

**Comment by j6mes** [comment]
I seem to remember it being about 50Gb

**Comment by OhadRubin** [comment]
I see.
Also, do you think it is possible to use [this](https://github.com/panx27/wikidata-dump-processor) to create the mongo dump?
Seems like it is the same format, and will take around 8 hours to process.

**Comment by dangiankit** [comment]
@j6mes When would the `mongo_wikidata_dump.gz` be available?

**Comment by johnson7788** [comment]
same issue, can't find the mongo_wikidata_dump.gz

**Comment by nicholas1022** [comment]
Could the mongo_wikidata_dump.gz be shared? Thanks.

**Comment by j6mes** [comment]
It has recently been uploaded to the page. Apologies for the delay.
