### ISSUE TITLE
How to obtain <path_to_mapped_kelm>.jsonl

### ISSUE THREAD

**Issue by urbanmatthias** [facebookresearch/NeuralDB#6]
Hi, regarding this:

> ## 1.2 KELM
> Importing the mappings from KELM is quite fast and is done through running the kelm_data.py script
> ```
> python -m ndb_data.data_import.kelm_data <path_to_mapped_kelm>.jsonl
> ```

How do I obtain the <path_to_mapped_kelm>.jsonl? I think it's not described in the readme. I guess it has something to do with the `map_kelm.py` script, but I wasn't able to figure the details. E.g. downloading KELM from https://github.com/google-research-datasets/KELM-corpus and feeding it into either `map_kelm.py` or `kelm_data.py` doesn't seem to work.

What am I missing?

**Comment by Rock-Anderson** [comment]
[Section-1](https://github.com/facebookresearch/NeuralDB/tree/main/dataset-construction#1-load-data-into-database) of the readme says - 

> The method for restoring the mapping between facts in the KELM and Wikidata IDs should now be considered as deprecated as the authors of KELM have now released the original mapping data.

Did you try downloading and providing the `entities.jsonl` from above mentioned KELM-corpus Github page to <path_to_mapped_kelm> option?

**Comment by j6mes** [comment]
The data was released before the KELM mapping was available. In subsequent work, I've not had to repeat these steps.  The instructions are still available for the purposes of replication.  The MognoDB dump with mappings has been uploaded to Google Drive now, but is about 20Gb
